server:
  port: 8001

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: yourpassword
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: service-edu
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.149.130
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0

#Enable circuit breaker
#feign:
#  hystrix:
#    enabled: true

##Default 1000ms
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 6000
#
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000

mybatis-plus:
  mapper-locations: classpath:com/atguigu/edu_service/mapper/xml/*.xml

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#logging:
#  level:
#    root: WARN